export type ArticleBlock = { heading?: string; paragraphs: string[] };

export const posts = [
  {
    slug: "ostrovni-pivovar-revoluce-v-energeticke-efektivite-potravinarskych-procesu",
    date: "24. 2. 2025",
    title: "Ostrovní Pivovar: Revoluce v Energetické Efektivitě Potravinářských Procesů",
    excerpt: "Nejnovější projekt Sunpower demonstruje maximální možnou energetickou efektivitu v potravinářských výrobních procesech.",
    images: ["/images/blog-pivovar.png", "/images/blog-pivovar-2.png"],
    blocks: [
      { paragraphs: ["Firma SUNPOWER s.r.o. se s hrdostí představuje svůj nejnovější projekt: „Ostrovní Pivovar“. Tento jedinečný mobilní zařízení je navrženo tak, aby demonstrovalo maximální možnou energetickou efektivitu v potravinářských výrobních procesech."] },
      { heading: "Partnerství se špičkami v oboru", paragraphs: ["SUNPOWER s.r.o. spolupracuje s předními českými odborníky a institucemi, včetně Jihočeské Univerzity a VUT Brno. Díky této spolupráci projekt čerpá z nejnovějších vědeckých poznatků a technologií, což mu umožňuje dosáhnout neuvěřitelné úrovně inovace."] },
      { heading: "Autonomní a šetrný k životnímu prostředí", paragraphs: ["Název „Ostrovní Pivovar“ není náhodný. Tento projekt je navržen tak, aby fungoval zcela autonomně, bez napojení na sítě. To znamená, že veškerá energie potřebná k výrobě potravinářských produktů, včetně tradičního českého piva, pochází z obnovitelných zdrojů. Díky tomu je celý výrobní proces bez negativních environmentálních dopadů, což je v souladu s vizí SUNPOWER s.r.o. o udržitelné budoucnosti."] },
      { heading: "Inovace v praxi", paragraphs: ["Ostrovní Pivovar bude sloužit jako mobilní demonstrační jednotka, která bude přinášet energeticky efektivní technologie do různých koutů České republiky a dále. Pivovar nejenže vyrábí produkty podle tradičních českých receptur, ale zároveň slouží jako vzdělávací nástroj, který ukazuje, jak lze dosáhnout maximální efektivity a minimálního dopadu na životní prostředí.", "Projekt Ostrovní Pivovar je důkazem toho, že inovace a udržitelnost mohou jít ruku v ruce. S hrdostí sledujeme, jak se tento projekt rozvíjí a těšíme se na jeho pozitivní dopad na potravinářský průmysl a životní prostředí.", "SUNPOWER s.r.o. – Váš partner pro udržitelnou energetiku.", "Bavíte se nad vizí budoucnosti? Dejte nám vědět, co si o našem projektu myslíte!"] },
    ] as ArticleBlock[],
  },
  { slug: "testovani-inovacniho-produktu-klimastena-2", date: "30. 10. 2024", title: "Testování inovačního produktu Klimastěna 2.0", excerpt: "Obrazová zpráva z testování inovačního produktu Klimastěna 2.0.", images: ["/images/blog-klimastena.png"], blocks: [] as ArticleBlock[] },
  { slug: "prototyp-bioreaktoru-k-vyrobe-organickeho-substratu", date: "10. 4. 2024", title: "PROTOTYP BIOREAKTORU, K VÝROBĚ ORGANICKÉHO SUBSTRÁTU", excerpt: "Informace o projektu prototypu bioreaktoru k výrobě organického substrátu.", images: ["/images/blog-bioreaktor.png"], blocks: [] as ArticleBlock[] },
  {
    slug: "zamek-cervena-lhota-projekt-vytapeni-chlazeni", date: "19. 10. 2023", title: "Zámek Červená Lhota – projekt vytápění/chlazení", excerpt: "Unikátní realizace tepelného čerpadla země/voda pro jednu z nejnavštěvovanějších českých památek.", images: ["/images/blog-zamek.jpg", "/images/blog-zamek-2.jpeg"],
    blocks: [
      { paragraphs: ["Dlouho připravovaná realizaci tepelného čerpadla země/voda pro zámek Červená Lhota začala. Jedná se o unikátní projekt, který je jedním z prvních svého druhu v České republice."] },
      { heading: "Historie a moderní technologie ruku v ruce", paragraphs: ["Zámek Červená Lhota je jednou z nejnavštěvovanějších památek v České republice. Jeho historický význam je nesporný, neboť byl postaven již ve 14. století. V průběhu staletí byl však několikrát přestavěn a dnes je v něm umístěno muzeum s bohatými sbírkami.", "V roce 2019 byl zámek uzavřen kvůli havarijnímu stavu hráze zámeckého rybníka. Charakter zámku a okolí se přímo nabízelo k využití pro vytápění tepelným čerpadlem země/voda a snížit tak jeho energetickou náročnost a zároveň chránit životní prostředí. Tepelné čerpadlo země/voda je ideální volbou pro tento účel, neboť využívá energii ze zemského tepla, která je obnovitelná a nezávislá na počasí."] },
      { heading: "Technické řešení", paragraphs: ["Tepelné čerpadlo je instalováno na dně zámeckého rybníka. K vytápění využívá horizontální kolektor, který je tvořen absorpčními kazetami. Tyto kazety snižují zabranou plochu kolektoru a zároveň zlepšují jeho účinnost.", "Tepelné čerpadlo má výkon 50 kW a je schopno vytopit přízemí zámku, bytovou jednotku na zámku, sbírky, obytné prostory v hospodářském křídle a půdní prostory systémem Klimastěna, pomocí kterého se bude topit i chladit.", "Z kotelny do zámku vede předizolované potrubí. Pro chlazení se bude využívat pasivní chlazení z kolektoru. V 1. patře zámku budou instalovány nízkoteplotní fancoily.", "Pro regulaci teploty jednotlivých místností bude instalován řídící systém. Ten bude zajišťovat i přípravu na efektivní regulaci podle dalších proměnných, jako je například využití obnovitelných zdrojů či krátkodobých trhů."] },
      { heading: "Ochrana a úspora", paragraphs: ["Díky tepelnému čerpadlu bude zámku stačit pouze jeden pracovník pro topení. Dále bude možné vyřadit akumulační kamna, která byla dosud využívána.", "Energetická úspora je odhadována na 75 %.", "Rekonstrukce vytápění zámku Červená Lhota je významným krokem pro ochranu tohoto kulturního dědictví. Tepelné čerpadlo země/voda je moderní a efektivní technologií, která zajistí zámku tepelnou pohodu a zároveň bude šetrná k životnímu prostředí."] },
    ] as ArticleBlock[],
  },
  { slug: "vyuziti-biologickych-odpadu-ke-zlepseni-energeticke-bilance-budov", date: "19. 10. 2023", title: "Využití biologických odpadů ke zlepšení energetické bilance budov", excerpt: "Projekt využití mikrobiální transformace biologických odpadů na teplo.", images: ["/images/blog-odpady.jpg"], blocks: [{ paragraphs: ["Využití biologických odpadů ke zlepšení energetické bilance budov s reg. číslem CZ.01.01.01/05/23_009/0001230", "Je poskytována finanční podpora od EU.", "Cílem je využít poznatky spojené s procesem Jean-Pain (využití mikrobiální transformace biologických odpadů na teplo) a získat tak unikátní konkurenční výhodu, potažmo snížit provozní náklady na obývání."] }] as ArticleBlock[] },
] as const;
